BlogSitesi/Controllers/DefaultController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace BlogSitesi.Controllers
{
    public class DefaultController : Controller
    {
        // GET: Default
        public ActionResult Index1()
        {
            return View();
        }
        public ActionResult Index2()
        {
            return View();
        }
    }
}

BlogSitesi/Controllers/KullaniciController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using BlogSitesi.Models;

namespace BlogSitesi.Controllers
{
    public class KullaniciController : Controller
    {
 
        [HttpGet]
        public ActionResult Sil(int id = 0)
        {
            User userModel = new User();
            return View(userModel);
        }

        [HttpPost]
        public ActionResult Sil(User userModel, Blog blogModel)
        {
            using (SiteEntities db = new SiteEntities())
            {
                User user = db.Users.Where(x => x.KullaniciAdi == userModel.KullaniciAdi && x.Sifre == userModel.Sifre).FirstOrDefault();
                if (user == null)
                {
                    userModel.LoginErrorMessage = "Kullanıcı adı veya şifre yanlış";
                    return View("Sil", userModel);
                }
                
                db.Users.Remove(user);
                db.SaveChanges();


            }
            ModelState.Clear();
            return RedirectToAction("KullaniciGiris", "Login");
        }        
        }



  
}

BlogSitesi/Controllers/UpdatePasswordController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using BlogSitesi.Models;

namespace BlogSitesi.Controllers
{
    public class UpdatePasswordController : Controller
    {
        public ActionResult Guncelleme()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Guncelleme(User customer)
        {
            using (SiteEntities entities = new SiteEntities())
            {
                User updatedCustomer = (from c in entities.Users
                    where c.KullaniciAdi == customer.KullaniciAdi
                    select c).FirstOrDefault();
     


                if (updatedCustomer != null)
                {
                    updatedCustomer.Sifre = customer.YeniSifre;
                    entities.SaveChanges();
                    ViewBag.SuccessMessage = "Sifre basariyla degistirildi";
                }
                else
                {
                    ViewBag.DuplicateMessage = "Kullanici bulunamadi";
                }

                return View();
            }
        }
    }
}

BlogSitesi/Views/Default/Index1.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Index1</title>
    <title>Venue - Responsive Web Template</title>

    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <link rel="stylesheet" href="~/templatemo_522_venue/css/bootstrap.min.css">
    <link rel="stylesheet" href="~/templatemo_522_venue/css/bootstrap-theme.min.css">
    <link rel="stylesheet" href="~/templatemo_522_venue/css/fontAwesome.css">
    <link rel="stylesheet" href="~/templatemo_522_venue/css/hero-slider.css">
    <link rel="stylesheet" href="~/templatemo_522_venue/css/owl-carousel.css">
    <link rel="stylesheet" href="~/templatemo_522_venue/css/datepicker.css">
    <link rel="stylesheet" href="~/templatemo_522_venue/css/templatemo-style.css">
    <link href="https://fonts.googleapis.com/css?family=Raleway:100,200,300,400,500,600,700,800,900" rel="stylesheet">
    <script src="~/templatemo_522_venue/js/vendor/modernizr-2.8.3-respond-1.4.2.min.js"></script>
</head>
<body>
    <div>
        <header style="background-color: sandybrown" id="header">
            <div class="container">
                <div class="row">
                    <div class="col-md-12">
                        <button id="primary-nav-button" type="button">Menu</button>
                        <nav id="primary-nav" class="dropdown cf">
                            <ul class="dropdown menu">
                                <li>
                                    <a style="color: white" href="#">HESABIM</a>
                                    <ul class="sub-menu">
                                        <li class='active'> <a style="color: black" href="@Url.Action("Guncelleme", "UpdatePassword")">Sifre Degistirme</a></li>
                                        <li class='active'> <a style="color: black" href="@Url.Action("Sil", "Kullanici")">Hesap Silme</a></li>
                                        <li class='active'> <a style="color: black" href="@Url.Action("Profil", "Admin")">Profil</a></li>
                                    </ul>
                                </li>
                                <li class='active'> <a style="color: black" href="@Url.Action("Guncelleme", "UpdatePassword")">Sifre Degistirme</a></li>
                                <li class='active'> <a style="color: black" href="@Url.Action("Sil", "Kullanici")">Hesap Silme</a></li>
                            </ul>
                        </nav><!-- / #primary-nav -->
                    </div>
                </div>
            </div>
        </header>
        @RenderBody()
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js" type="text/javascript"></script>
        <script>window.jQuery || document.write('<script src="js/vendor/jquery-1.11.2.min.js"><\/script>')</script>

        <script src="~/templatemo_522_venue/js/vendor/bootstrap.min.js"></script>

        <script src="~/templatemo_522_venue/js/datepicker.js"></script>
        <script src="~/templatemo_522_venue/js/plugins.js"></script>
        <script src="~/templatemo_522_venue/js/main.js"></script>

    </div>
</body>
</html>

BlogSitesi/Views/Default/Index2.cshtml
@{
    ViewBag.Title = "Index2";
    Layout = "~/Views/Default/Index1.cshtml";
}

<h2>Index2</h2>