BlogSitesi/Controllers/RecordController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using BlogSitesi.Models;
using System.IO;


namespace BlogSitesi.Controllers
{
    public class RecordController : Controller
    {
            [HttpGet]
            public ActionResult Kayit(int id = 0)
            {
                User userModel = new User();
                return View(userModel);
            }

            [HttpPost]
            public ActionResult Kayit(User userModel)
            {
        
            using (SiteEntities dbModel1 = new SiteEntities())
            {
                string fileName = Path.GetFileNameWithoutExtension(userModel.Imagefile.FileName);
                string extension = Path.GetExtension(userModel.Imagefile.FileName);
                fileName = fileName + DateTime.Now.ToString("yymmssfff") + extension;
                userModel.Profil = "~/Image/" + fileName;
                fileName = Path.Combine(Server.MapPath("~/Image/"), fileName);
                userModel.Imagefile.SaveAs(fileName); 
                    if (dbModel1.Users.Any(x => x.KullaniciAdi == userModel.KullaniciAdi))
                    {
                        ViewBag.DuplicateMessage = "Kullanıcı Adı Alınmış";
                        return View("Kayit", userModel);
                    }

                    dbModel1.Users.Add(userModel);
                    dbModel1.SaveChanges();
                }
                ModelState.Clear();
                ViewBag.SuccessMessage = "KAYIT BAŞARILI";
                return View("Kayit", new User());

            }
        }
}

BlogSitesi/Views/Record/Kayit.cshtml
@model BlogSitesi.Models.User
@{
    Layout = null;
}


<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <title>Daily UI - Day 1 Sign In</title>
    <link href='https://fonts.googleapis.com/css?family=Roboto+Slab:400,100,300,700|Lato:400,100,300,700,900' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" href="~/logintemp/css/style.css">
</head>

<body>
    <div class="container">
        <div class="login-box animated fadeInUp">
            <div class="box-header">
                <h2>KAYIT OL</h2>
            </div>
            @using (Html.BeginForm("Kayit", "Record", FormMethod.Post, new { enctype = "multipart/form-data" }))
            {
                @Html.AntiForgeryToken()

        <div class="form-horizontal">

            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div style="margin-left: auto; margin-right: auto" class="form-group">
                <div class="col-md-2">
                    <h5>Kullanici Adi</h5>
                    @Html.EditorFor(model => model.KullaniciAdi, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.KullaniciAdi, "", new { @class = "text-danger" })
                </div>
            </div>
            <div style="margin-left: auto; margin-right: auto" class="form-group">
                <div class="col-md-2">
                    <h5>Sifre</h5>
                    @Html.EditorFor(model => model.Sifre, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Sifre, "", new { @class = "text-danger" })
                </div>
            </div>
            <div style="margin-left: auto; margin-right: auto" class="form-group">
                <div class="col-md-2">
                    @Html.EditorFor(model => model.TekrarSifre, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.TekrarSifre, "", new { @class = "text-danger" })
                </div>
            </div>
         <div style="margin-left: auto; margin-right: auto" class="form-group">
                <div class="col-md-2">
                    <h4>Profil Resmi</h4>
                    <input type="file" name="Imagefile" required />
                </div>
            </div>  
            <button type="submit">Giris</button>
            <div class="form-group">
                <div class="col-md-offset-2 col-md-2">
                    <label class="label-success">@ViewBag.SuccessMessage</label>
                </div>
            </div>
            <div class="form-group">
                <div class="col-md-offset-2 col-md-2">
                    <label class="danger-success">@ViewBag.DuplicateMessage</label>
                </div>
            </div>

            <br />
            <a href="@Url.Action("KullaniciGiris", "Login")">Giris yap Sayfasi</a>
        </div>              
            }
        </div>
    </div>
</body>
</html>